### ISSUE TITLE
Unable to find host target for Pods-PubNubPlayground

### ISSUE THREAD

**Issue by gsusie** [pubnub/Playgrounds#5]
attempting to run pod install results in this error:

Analyzing dependencies
[!] Unable to find host target for Pods-PubNubPlayground. Please add the host targets for the embedded targets to the Podfile.

Perhaps a missing file or directory layout? 
Thanks for your help on this, greatly appreciated...

**Comment by jzucker2** [comment]
Looking into this now. Thank you

**Comment by jzucker2** [comment]
@nimble
Maybe you should try `pod repo update` before running `pod install`

Also, what version of Cocoapods are you using? This is only intended to support Cocoapods 1.0.0 and up

**Comment by gsusie** [comment]
Thanks for your fast reply!  I'm running Cocoapods 1.1.0.beta.1 and I tried the command: pod repo  update which pulled a few files down with it but I'm still getting the same error.

**Comment by gsusie** [comment]
I think I fixed my problem. I downgraded Cocoapods to 1.0.1 with the following command: 
 pod _1.0.1_ install. Everything worked!  Thanks again for your help!

**Comment by jzucker2** [comment]
Seems like other people have noticed this issue with Cocoapods 1.1.0.beta1 https://github.com/CocoaPods/CocoaPods/issues/5620
